# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccx < Formula
  desc "Zero-config Claude Pro/Max plan credit-limit window tracker"
  homepage "https://github.com/seosd97/cc-token-exposer"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.2.0/ccx_darwin_amd64.tar.gz"
      sha256 "1b58b69dc4705a828fd51bc84b29d82e3213c840ff7135d05752e8060e3fb914"

      define_method(:install) do
        bin.install "ccx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.2.0/ccx_darwin_arm64.tar.gz"
      sha256 "261f3d677cc0ab144cc9789a58bcf037ddb0b4d15e0eb8c1e8ac0944b3651efe"

      define_method(:install) do
        bin.install "ccx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.2.0/ccx_linux_amd64.tar.gz"
      sha256 "4d1624521b174cd5cee02e6499db1986a61cf5f53027038168719d1ffa2b82f6"
      define_method(:install) do
        bin.install "ccx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.2.0/ccx_linux_arm64.tar.gz"
      sha256 "085c4d66e68c72b9f6a085b4139f31806b601716c7ca61b1d935f5ac99789423"
      define_method(:install) do
        bin.install "ccx"
      end
    end
  end

  test do
    system "#{bin}/ccx", "version"
  end
end
