# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccx < Formula
  desc "Zero-config Claude Pro/Max plan credit-limit window tracker"
  homepage "https://github.com/seosd97/cc-token-exposer"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.3.0/ccx_darwin_amd64.tar.gz"
      sha256 "e36d4c9b279c51400ca996f6852bdee8adbf30cd8501e9826f13ccf71ab1b7f8"

      define_method(:install) do
        bin.install "ccx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.3.0/ccx_darwin_arm64.tar.gz"
      sha256 "3e929296eb6aef6b62d35c9653ba559e8480e02887710b712abc727f4921ef28"

      define_method(:install) do
        bin.install "ccx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.3.0/ccx_linux_amd64.tar.gz"
      sha256 "b9bdd25f41e58dc941a0879414c1fa93fccaafd548b75e94fe9061f87791e7e5"
      define_method(:install) do
        bin.install "ccx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.3.0/ccx_linux_arm64.tar.gz"
      sha256 "a180eb3cfc6a59943f51ae29db584ebf9715b59b7e6f177b62d24f94e8b682a2"
      define_method(:install) do
        bin.install "ccx"
      end
    end
  end

  test do
    system "#{bin}/ccx", "version"
  end
end
