# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ccx < Formula
  desc "Zero-config Claude Pro/Max plan credit-limit window tracker"
  homepage "https://github.com/seosd97/cc-token-exposer"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.1.0/ccx_darwin_amd64.tar.gz"
      sha256 "214016afca909afc809063a260718b069de1842216c2ebcb75ef19810473f6e6"

      define_method(:install) do
        bin.install "ccx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.1.0/ccx_darwin_arm64.tar.gz"
      sha256 "3b1eeccfcb482f8be777c42b011fd5979144bc83069391ce330ea5d70534464a"

      define_method(:install) do
        bin.install "ccx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.1.0/ccx_linux_amd64.tar.gz"
      sha256 "9bb5de666bf2dd1f7d14ded22e9e02138f842076aa0d07454dcdd20179bc47e1"
      define_method(:install) do
        bin.install "ccx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/seosd97/cc-token-exposer/releases/download/v0.1.0/ccx_linux_arm64.tar.gz"
      sha256 "aad02544bf8cb7443676a213a5827016d3101ad01163eb20171a9f9c79cbad33"
      define_method(:install) do
        bin.install "ccx"
      end
    end
  end

  test do
    system "#{bin}/ccx", "version"
  end
end
